### ISSUE TITLE
redirection vers authentification yunohost pour le module cdav

### ISSUE THREAD

**Issue by smrhp** [YunoHost-Apps/dolibarr_ynh#67]
### Describe the bug

L'utilisation de l'accès en caldav via le module cdav (https://github.com/Befox/cdav/blob/e7ba4efe9e699fb729f68c569f791316b5d64d13/README.md) me redirige vers l'authentification yunohost

### Context

- Hardware: VM dédiée à yunohost
- YunoHost version: 4.2.8.3

J'ai tenté d'ajouter les commandes indiquées dans le readme du module pour nginx, mais l'authentification n'est pas demandée lors de l'ajout du lien caldav dans thunderbird. cela redirige vers l'url sso de yunohost et du coup l'authentification est impossible (car thunderbird ne présente pas l'interface web de login)

ce type d'utilisation est-il possible/compatible avec dolibarr sur yunohost ? (je connais assez bien nginx/debian & cie, mais beaucoup moins yunohost, il n'est donc pas impossible que je passe à côté d'une option de configuration)

**Comment by mastereur** [comment]
Bonjour,

Actuellement, et du fait que l'application n'est pas publique, il ne seras pas possible de faire fonctionner CALDAV. A contrario de Nextcloud qui a les connexions DAV fonctionnelles car c'est une application publique.

Il y aurait peut être une solution (non testé) où il faudrait changer l'autorisation "Dolibarr" dans les "Groupes et autorisations" en passant de ce fait Dolibarr en publique. De même en corrélation, la méthode d'authentification doit changer.

Si l'on suis les indications sur [https://wiki.dolibarr.org/index.php?title=Fichier_de_configuration](https://wiki.dolibarr.org/index.php?title=Fichier_de_configuration), il faut changer `$dolibarr_main_authentication="http"` par `$dolibarr_main_authentication="ldap"` au mieux ou bien par défaut à `$dolibarr_main_authentication="dolibarr"`.
La configuration LDAP sera a faire.

Tenez moi informé si vous y êtes arrivé.
---
Hello,
At the moment, and because the application is not public, it will not be possible to run CALDAV. On the contrary of Nextcloud which has functional DAV connections because it is a public application.

There could be a solution (not tested) where you have to change the authorization "Dolibarr" in the "Groups and authorizations" by making Dolibarr public. Also  at the same time, the authentication method must change.

If you follow the indications on [https://wiki.dolibarr.org/index.php?title=Fichier_de_configuration](https://wiki.dolibarr.org/index.php?title=Fichier_de_configuration), you must change `$dolibarr_main_authentication="http"` by `$dolibarr_main_authentication="ldap"` at best or by default to `$dolibarr_main_authentication="dolibarr"`.
The LDAP configuration must be done.

Let me know if you succeed.

**Comment by mastereur** [comment]
Bonjour,

Avez-vous réussi ce que vous vouliez faire ?

---
Hello,

Did you succeed in what you wanted to do?
