### ISSUE TITLE
Dolibarr user is always SuperAdmin, not the yunohost user

### ISSUE THREAD

**Issue by polytan02** [YunoHost-Apps/dolibarr_ynh#70]
Hello,

I just installed Dolibarr on Yunohost (both on latest stable versions), but the user in Dolibar is always listed as SuperAdmin, and not the current Yunohost user.

Did I miss something ?

**Comment by mastereur** [comment]
Hello,

I redid the test with installation of Dolibarr and yunohost with 2 users (Me and a Test).

The SuperAdmin user is the one chosen during the installation but it is possible to modify the name from Dolibarr.
The name Superadmin is a limitation due to the automatic installation

Also, if I connect with Test user on Yunohost, Dolibarr access is done well on Test
